#!/usr/bin/env python
"""E11 — bear-market disable switch for E8-A (pooled GBDT gate top10% x tp0.5%/sl2%/to48 long).

Background (docs/strategy-lab.md E8/E8-A crash test): E8-A holdout
(2025-10..2026-07) 80.6%/+16.0bp (n=62), but in the crash window
(2021-10..2023-01, time-clean model) 71.2%/-20.7bp (n=177) and anti-selected.
Question: can a REAL-TIME computable regime switch cut the crash-window loss
while keeping the holdout gain?

Switch candidates (registered up front, ONLY these 5 to limit switch-level
overfitting; all daily indicators from 5m->daily closes, applied with shift(1):
today's on/off state is decided by YESTERDAY's close):
  S1: disable when close < 200d SMA
  S2: disable when drawdown from 252d rolling high > 20%
  S3: disable when 50d SMA < 200d SMA (death cross)
  S4: S1 OR S2
  S5: control — no switch

Test protocol (REUSES the two existing experiments' trade streams, no model
retraining):
- Crash leg: the 177 gated trades in outputs/e8a_crash_test/trades.csv
  (variant=gated_top10, time-clean 2019-2021-trained pooled model), filtered by
  the switch state on each trade's ET day.
- Holdout leg: the E8-A 62 entries. No trades file exists in outputs/e8_pooled
  (frontier_shift.csv stores only aggregates), so they are REGENERATED by
  replaying the exact e8_pooled_gbdt pipeline (a_leave_tsla_out model,
  retention-matched gate 0.70 -> new-prob quantile, E9 settlement machinery)
  and asserted against the stored aggregates (n=62, WR 80.65%, +15.97bp).
- Metrics per switch per leg: n / WR / avg bp / compounded total / closed-trade
  MDD / bar-level MTM MDD (mtm_equity_path from e8a_crash_test: marks open
  positions at 5m closes, flat between trades; removing trades keeps the
  remaining trades' fills unchanged — a live switch could have admitted other
  overlapping events, so filtered streams are an approximation, noted).
- Key table: crash-loss cut % vs holdout-gain kept %.
- Latency: trading days from the crash peak until the switch first disables;
  loss already eaten before that (share of the unfiltered crash loss); trading
  days from the bottom until it re-enables.
- Combined view: crash leg then holdout leg chained into one hypothetical
  equity line (two DIFFERENT model instances + a 2023-02..2025-09 gap — an
  approximation, stated as such).

Multiple comparisons: 5 switches = 5 comparisons (S5 is the control), recorded
as such in the ledger.

Usage:  .venv/bin/python research/e11_bear_switch.py
Outputs: outputs/e11_bear_switch/{switch_table.csv, latency.csv, summary.txt}
"""

from __future__ import annotations

import sys
import time
from datetime import date
from pathlib import Path

import numpy as np
import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

import research.e8_pooled_gbdt as e8  # noqa: E402
from research.e8a_crash_test import mdd, mtm_equity_path  # noqa: E402
from research.e9_frontier_search import BarSet, run_combo, seg_stats, signals_A  # noqa: E402
from research.ml_common import make_lgbm  # noqa: E402
from src.common.data_io import ET, load_bars  # noqa: E402

# ----------------------------------------------------------------- parameters
OUT = ROOT / "outputs" / "e11_bear_switch"
CRASH_TRADES = ROOT / "outputs" / "e8a_crash_test" / "trades.csv"
CRASH_BARS = ROOT / "data" / "pool_crash" / "TSLA_5m_2019_2023.csv"
OLD_SCORES = ROOT / "outputs" / "ml_filter_3y" / "per_event_scores.csv"

TP, SL, TIMEOUT = 0.005, 0.020, 48
E9_GATE = 0.70                      # the E9 gate whose retention defines E8-A
CRASH_START, CRASH_END = date(2021, 10, 1), date(2023, 1, 31)

# stored E8-A holdout aggregates (outputs/e8_pooled/frontier_shift.csv) used
# as a reproduction assertion, never as a result source
EXP_N, EXP_WR, EXP_AVG_BP = 62, 0.8064516129032258, 15.965470720673224

SWITCHES = {
    "S1": "收盘 < 200日SMA 停用",
    "S2": "距252日滚动高点回撤 > 20% 停用",
    "S3": "50日SMA < 200日SMA（死叉）停用",
    "S4": "S1 OR S2",
    "S5": "对照：无开关",
}


# ------------------------------------------------------------- switch states
def daily_closes(bars: pd.DataFrame) -> pd.Series:
    et_days = bars.index.tz_convert(ET).date
    return bars["Close"].groupby(et_days).last()


def switch_states(dc: pd.Series) -> pd.DataFrame:
    """True = strategy DISABLED that day. shift(1): today's state is decided
    by yesterday's close (real-time computable, no lookahead)."""
    sma200 = dc.rolling(200).mean()
    sma50 = dc.rolling(50).mean()
    hi252 = dc.rolling(252).max()
    off = pd.DataFrame(index=dc.index)
    off["S1"] = dc < sma200
    off["S2"] = dc / hi252 - 1.0 < -0.20
    off["S3"] = sma50 < sma200
    off["S4"] = off["S1"] | off["S2"]
    off["S5"] = False
    state = off.shift(1).fillna(False).astype(bool)
    state.attrs["ind_valid_from"] = sma200.dropna().index[0] if sma200.notna().any() else None
    return state


def apply_switch(trades: pd.DataFrame, state: pd.Series) -> pd.DataFrame:
    on = ~trades["et_day"].map(state).fillna(False).astype(bool)
    return trades[on].reset_index(drop=True)


def leg_metrics(trades: pd.DataFrame, bs: BarSet) -> dict:
    st = seg_stats(trades, "x")
    n = st["x_n"]
    return {
        "n": n,
        "wr": st["x_wr"] if n else np.nan,
        "avg_bp": st["x_avg_bp"] if n else np.nan,
        "total": st["x_total"] if n else 0.0,
        "mdd_closed": st["x_mdd"] if n else 0.0,
        "mtm_mdd": mdd(mtm_equity_path(bs, trades, TP, SL, TIMEOUT)) if n else 0.0,
    }


# ------------------------------------------------- holdout trades regeneration
def regenerate_holdout_trades() -> tuple[pd.DataFrame, BarSet, pd.DataFrame, str]:
    """Replay e8_pooled_gbdt's a_leave_tsla_out inference + retention-matched
    gate-0.70 threshold + E9 settlement to recover the 62 E8-A holdout trades."""
    frames = []
    for sym in e8.POOL_SYMBOLS + [e8.TARGET]:
        got = e8.build_symbol_dataset(sym)
        if got is None:
            raise SystemExit(f"[{sym}] bars/events missing — cannot regenerate E8-A trades")
        frames.append(got[0])
    all_ds = e8.add_normalized_features(pd.concat(frames, ignore_index=True))
    feat_ok = all_ds[e8.POOLED_FEATURES[:-1]].notna().all(axis=1)
    all_ds = all_ds[feat_ok].reset_index(drop=True)

    is_tsla = all_ds["symbol"].astype(str) == e8.TARGET
    loo_train = all_ds[(~is_tsla) & (all_ds["et_day"] < e8.TRAIN_END)]
    tsla_hold = all_ds[is_tsla & (all_ds["et_day"] >= e8.HOLDOUT_START)].reset_index(drop=True)

    model = make_lgbm(e8.SEED)
    model.fit(loo_train[e8.POOLED_FEATURES], loo_train["label"])
    probs = model.predict_proba(tsla_hold[e8.POOLED_FEATURES])[:, 1]

    bars = load_bars(str(e8.TSLA_BARS))
    bs = BarSet(bars)
    scores = tsla_hold[["entry_t"]].copy()
    scores["prob"] = probs
    scores["epos"] = bars.index.get_indexer(pd.DatetimeIndex(scores["entry_t"]))
    scores = scores[scores["epos"] >= 0].sort_values("epos").reset_index(drop=True)

    old = pd.read_csv(OLD_SCORES)
    old = old[old["prob"].notna()].copy()
    old["et_day"] = pd.to_datetime(old["et_day"]).dt.date
    old_hold = old[old["et_day"] >= e8.HOLDOUT_START]
    retention = float((old_hold["prob"] >= E9_GATE).mean())
    thr = float(np.quantile(scores["prob"].to_numpy(), 1.0 - retention))

    trades = run_combo(bs, signals_A(bs, scores, thr, session=False), TP, SL, TIMEOUT)
    st = seg_stats(trades, "h")
    src = (f"重放 e8_pooled_gbdt（a_leave_tsla_out，gate0.70 保留率匹配阈值 {thr:.4f}）："
           f"n={st['h_n']}, WR={st['h_wr']:.1%}, avg={st['h_avg_bp']:+.2f}bp")
    if not (st["h_n"] == EXP_N and abs(st["h_wr"] - EXP_WR) < 1e-6
            and abs(st["h_avg_bp"] - EXP_AVG_BP) < 0.05):
        src += (f"  [警告] 与 frontier_shift.csv 存档 (n={EXP_N}, WR={EXP_WR:.1%}, "
                f"avg={EXP_AVG_BP:+.2f}bp) 不一致——以重放结果为准，如实记录")
    else:
        src += "  —— 与 frontier_shift.csv 存档一致（重放验证通过）"
    return trades, bs, bars, src


# ------------------------------------------------------------------- latency
def latency_row(sw: str, state: pd.Series, crash_trades_all: pd.DataFrame,
                s5_crash_total: float, peak_day, bottom_day,
                hold_state: pd.Series, hold_days: pd.Index) -> dict:
    days = state.index
    pos = {d: i for i, d in enumerate(days)}
    pk, bt = pos[peak_day], pos[bottom_day]

    off_idx = [i for i in range(pk, len(days)) if state.iloc[i]]
    if off_idx:
        off_date = days[off_idx[0]]
        off_lag = off_idx[0] - pk
        pre = crash_trades_all[crash_trades_all["et_day"] < off_date]
        loss_before = float(np.prod(1 + pre["ret"].to_numpy()) - 1) if len(pre) else 0.0
        share = loss_before / s5_crash_total if s5_crash_total < 0 else np.nan
    else:
        off_date, off_lag, loss_before, share = None, np.nan, np.nan, np.nan
        pre = crash_trades_all.iloc[0:0]

    reopen_idx = [i for i in range(bt, len(days)) if not state.iloc[i]]
    if off_idx and reopen_idx and reopen_idx[0] >= off_idx[0]:
        reopen_date, reopen_lag = days[reopen_idx[0]], reopen_idx[0] - bt
    else:
        reopen_date, reopen_lag = None, np.nan

    crash_days = [d for d in days if CRASH_START <= d <= CRASH_END]
    return {
        "switch": sw, "desc": SWITCHES[sw],
        "crash_peak_day": peak_day, "off_date": off_date, "off_lag_tdays": off_lag,
        "trades_before_off": len(pre), "loss_before_off": loss_before,
        "share_of_S5_crash_loss": share,
        "bottom_day": bottom_day, "reopen_date": reopen_date,
        "reopen_lag_tdays": reopen_lag,
        "crash_off_days": int(state.loc[crash_days].sum()),
        "crash_window_days": len(crash_days),
        "holdout_off_days": int(hold_state.loc[hold_days].sum()),
        "holdout_window_days": len(hold_days),
    }


# ------------------------------------------------------------------------ main
def main() -> None:
    t0 = time.time()
    OUT.mkdir(parents=True, exist_ok=True)

    # ---------------- crash leg inputs ---------------------------------------
    crash_bars = load_bars(str(CRASH_BARS))
    bs_c = BarSet(crash_bars)
    tr_c = pd.read_csv(CRASH_TRADES)
    tr_c = tr_c[tr_c["variant"] == "gated_top10"].copy()
    tr_c["et_day"] = pd.to_datetime(tr_c["et_day"]).dt.date
    tr_c = tr_c[["epos", "et_day", "ret"]].reset_index(drop=True)
    # settlement consistency: replayed rets must equal the stored ones
    for _, t in tr_c.iterrows():
        got = bs_c.eval_trade(int(t["epos"]), 1, TP, SL, TIMEOUT)
        assert got is not None and abs(got[0] - t["ret"]) < 1e-9, "crash trade replay mismatch"
    print(f"crash leg: {len(tr_c)} gated trades loaded & replay-verified")

    # ---------------- holdout leg (regenerated E8-A trades) ------------------
    tr_h, bs_h, hold_bars, hold_src = regenerate_holdout_trades()
    print(hold_src)

    # ---------------- daily switch states ------------------------------------
    dc_c = daily_closes(crash_bars)
    dc_h = daily_closes(hold_bars)
    st_c = switch_states(dc_c)
    st_h = switch_states(dc_h)
    hold_days = pd.Index([d for d in dc_h.index if d >= e8.HOLDOUT_START])
    # indicator warm-up must be complete before each test window
    assert dc_c.rolling(252).max().dropna().index[0] < CRASH_START
    assert dc_h.rolling(252).max().dropna().index[0] < e8.HOLDOUT_START

    crash_daily = dc_c[(dc_c.index >= CRASH_START) & (dc_c.index <= CRASH_END)]
    peak_day = crash_daily.idxmax()          # 2021-11 top
    bottom_day = dc_c[dc_c.index >= peak_day].idxmin()  # 2023-01 bottom

    # ---------------- per-switch metrics -------------------------------------
    s5_crash = leg_metrics(tr_c, bs_c)
    s5_hold = leg_metrics(tr_h, bs_h)

    rows, lat_rows = [], []
    for sw, desc in SWITCHES.items():
        c_kept = apply_switch(tr_c, st_c[sw])
        h_kept = apply_switch(tr_h, st_h[sw])
        mc, mh = leg_metrics(c_kept, bs_c), leg_metrics(h_kept, bs_h)
        loss_cut = (1.0 - mc["total"] / s5_crash["total"]) if s5_crash["total"] < 0 else np.nan
        gain_kept = (mh["total"] / s5_hold["total"]) if s5_hold["total"] > 0 else np.nan
        comb_rets = np.r_[c_kept["ret"].to_numpy(), h_kept["ret"].to_numpy()]
        comb_eq = np.cumprod(1 + comb_rets) if len(comb_rets) else np.array([1.0])
        rows.append({
            "switch": sw, "desc": desc,
            "crash_n": mc["n"], "crash_wr": mc["wr"], "crash_avg_bp": mc["avg_bp"],
            "crash_total": mc["total"], "crash_mtm_mdd": mc["mtm_mdd"],
            "crash_loss_cut_pct": loss_cut,
            "hold_n": mh["n"], "hold_wr": mh["wr"], "hold_avg_bp": mh["avg_bp"],
            "hold_total": mh["total"], "hold_mtm_mdd": mh["mtm_mdd"],
            "hold_gain_kept_pct": gain_kept,
            "combined_total": float(comb_eq[-1] - 1),
            "combined_mdd_closed": mdd(comb_eq),
        })
        lat_rows.append(latency_row(sw, st_c[sw], tr_c, s5_crash["total"],
                                    peak_day, bottom_day, st_h[sw], hold_days))
        print(f"{sw}: crash n={mc['n']:>3} total={mc['total']:+.2%} cut={loss_cut:.0%} | "
              f"hold n={mh['n']:>2} total={mh['total']:+.2%} kept={gain_kept:.0%}")

    tab = pd.DataFrame(rows)
    lat = pd.DataFrame(lat_rows)
    tab.to_csv(OUT / "switch_table.csv", index=False)
    lat.to_csv(OUT / "latency.csv", index=False)

    # ---------------- verdict -------------------------------------------------
    cand = tab[(tab["switch"] != "S5")
               & (tab["crash_loss_cut_pct"] > 0.70) & (tab["hold_gain_kept_pct"] > 0.80)]
    best = (cand.sort_values("combined_total", ascending=False).iloc[0]
            if len(cand) else None)

    def pct(x, digits=0):
        return "n/a" if not np.isfinite(x) else f"{x:.{digits}%}"

    L = []
    L.append("E11 — E8-A 熊市停用开关（S1..S4 + 对照 S5；日频指标 shift(1)，实时可计算）")
    L.append("=" * 100)
    L.append("协议（先于结果写死）：")
    L.append("- 只测预登记的 5 个开关（S1 收盘<200日SMA / S2 距252日高点回撤>20% / S3 50日SMA<200日SMA 死叉 /")
    L.append("  S4 = S1 OR S2 / S5 无开关对照），防止开关本身过拟合；5 次比较如实记账。")
    L.append("- 开关状态由前一交易日收盘决定（shift(1)，无前视）；日线由 5m RTH 聚合。")
    L.append("- 不重训模型：崩盘段复用 outputs/e8a_crash_test/trades.csv 门控组 177 笔（2019-2021 时序干净池模型）；")
    L.append(f"  留出段 62 笔无存档交易明细，来源 = {hold_src}")
    L.append("- 达标线（先写死）：最优开关须 崩盘损失削减 >70% 且 留出收益保留 >80% → 有条件通过交 shadow；")
    L.append("  否则判死。")
    L.append("")
    L.append("== 开关 x 两段 二维表（崩盘损失削减 % vs 留出收益保留 %）==")
    hdr = (f"{'开关':<4} {'崩n':>4} {'崩WR':>6} {'崩avg':>8} {'崩total':>8} {'崩MTM MDD':>9} "
           f"{'损失削减':>7} | {'留n':>3} {'留WR':>6} {'留avg':>8} {'留total':>7} {'收益保留':>7} "
           f"| {'拼接total':>8} {'拼接MDD':>7}")
    L.append(hdr)
    for _, r in tab.iterrows():
        L.append(
            f"{r['switch']:<4} {r['crash_n']:>4} {pct(r['crash_wr'],1):>6} "
            f"{('n/a' if not np.isfinite(r['crash_avg_bp']) else f'{r.crash_avg_bp:+.1f}bp'):>8} "
            f"{r['crash_total']:>+8.2%} {r['crash_mtm_mdd']:>9.2%} {pct(r['crash_loss_cut_pct']):>7} | "
            f"{r['hold_n']:>3} {pct(r['hold_wr'],1):>6} "
            f"{('n/a' if not np.isfinite(r['hold_avg_bp']) else f'{r.hold_avg_bp:+.1f}bp'):>8} "
            f"{r['hold_total']:>+7.2%} {pct(r['hold_gain_kept_pct']):>7} | "
            f"{r['combined_total']:>+8.2%} {r['combined_mdd_closed']:>7.2%}")
    L.append("（崩盘段 MTM MDD 为 5m bar 级逐 bar 盯市；拼接 MDD 为逐笔已平仓近似——两段模型实例不同、")
    L.append("  且 2023-02..2025-09 之间无交易流，拼接曲线仅为量级参考，不是可交易权益曲线。）")
    L.append("")
    L.append("== 开关延迟（滞后指标的代价）==")
    L.append(f"崩盘顶点（窗口内日线收盘最高）= {peak_day}；底部 = {bottom_day}（数据止于 {dc_c.index[-1]}）")
    for _, r in lat.iterrows():
        if r["switch"] == "S5":
            L.append(f"{r['switch']}: 无开关（对照），不关闸不开闸")
            continue
        off_s = (f"关闸 {r['off_date']}（顶点后 {int(r['off_lag_tdays'])} 个交易日），"
                 f"关闸前已成交 {int(r['trades_before_off'])} 笔、已吃 {r['loss_before_off']:+.2%}"
                 f"（占 S5 崩盘段总亏损 {pct(r['share_of_S5_crash_loss'])}）"
                 if pd.notna(r["off_lag_tdays"]) else "整个窗口未关闸")
        re_s = (f"；底部后 {int(r['reopen_lag_tdays'])} 个交易日（{r['reopen_date']}）重新开闸"
                if pd.notna(r["reopen_lag_tdays"]) else "；数据结束前未重新开闸")
        L.append(f"{r['switch']}: {off_s}{re_s}；崩盘窗口内停用 "
                 f"{int(r['crash_off_days'])}/{int(r['crash_window_days'])} 天，"
                 f"留出窗口内停用 {int(r['holdout_off_days'])}/{int(r['holdout_window_days'])} 天")
    L.append("")

    L.append("== 判读 ==")
    if best is not None:
        L.append(f"1. 达标开关存在：{best['switch']}（{best['desc']}）——崩盘损失削减 "
                 f"{pct(best['crash_loss_cut_pct'])}（total {s5_crash['total']:+.2%} → "
                 f"{best['crash_total']:+.2%}），留出收益保留 {pct(best['hold_gain_kept_pct'])}"
                 f"（{s5_hold['total']:+.2%} → {best['hold_total']:+.2%}）。")
        L.append("   判定：【有条件通过】——E8-A + " + best["switch"] +
                 " 一起交 shadow 前向验证（>=8 周），开关规则随策略一同冻结，不得再调。")
    else:
        L.append("1. 无开关同时满足『崩盘损失削减>70% 且 留出收益保留>80%』。判定：【判死】——")
        L.append("   预登记的 5 个实时开关救不了 E8-A 的崩盘段反选，或代价是牺牲留出段收益。")
    if best is not None:
        avg_diff = best["crash_avg_bp"] - s5_crash["avg_bp"]
        if abs(avg_diff) < 3.0:
            L.append(f"   注意削减的来源：{best['switch']} 崩盘段剩余 {int(best['crash_n'])} 笔的单笔期望 "
                     f"{best['crash_avg_bp']:+.1f}bp，与 S5 的 {s5_crash['avg_bp']:+.1f}bp 同量级——"
                     "损失削减几乎全部来自停用天数（空仓），不是开关挑出了更好的交易；门在开闸时段依旧反选。")
        if np.isfinite(best["hold_gain_kept_pct"]) and best["hold_gain_kept_pct"] > 1.0:
            L.append(f"   留出保留 >100% 的解释：留出窗口内 TSLA 也有触发开关的时段，被删的 "
                     f"{int(s5_hold['n'] - best['hold_n'])} 笔净为亏损——方向与假设一致，"
                     "但这是同一留出段的又一次事后观察，不作为加分证据（n 由 "
                     f"{int(s5_hold['n'])} 降至 {int(best['hold_n'])}）。")
    lr = lat[lat["switch"] != "S5"]
    if len(lr):
        lag_min = lr["off_lag_tdays"].min()
        eaten = lr.loc[lr["off_lag_tdays"].idxmin() if lr["off_lag_tdays"].notna().any() else lr.index[0]]
        L.append(f"2. 迟到代价（预警兑现）：最快的开关也在顶点后 {int(lag_min) if np.isfinite(lag_min) else '∞'} "
                 f"个交易日才关闸；最快者关闸前已吃 {eaten['loss_before_off']:+.2%}"
                 f"（占 S5 总亏损 {pct(eaten['share_of_S5_crash_loss'])}）——200SMA/回撤 20% 都是滞后指标，"
                 "顶部附近的亏损无法靠这类开关避免，只能截断后续。")
    L.append("3. 多重比较记账：本实验 5 个开关 = 5 次比较（S5 为对照），全部预登记、无网格；")
    L.append("   即便最优开关达标，也只是『一次通过』，效力由 shadow 前向裁决。")
    L.append("4. 诚实性备注：")
    L.append("   - 两段交易流来自两个不同的模型实例（崩盘段 2019-2021 池训练；留出段 2023-2025 池训练），")
    L.append("     开关叠加在『同一配方』上而非同一模型上；拼接权益曲线是近似。")
    L.append("   - 过滤只是从既有交易流中删单：实盘中开关停用期间不占仓，重新开闸后的交易与回放一致，")
    L.append("     但『停用期释放的仓位本可承接其他重叠事件』这类二阶效应未建模（本配置同一时刻单仓、日内平，影响很小）。")
    L.append("   - 留出段 62 笔本身 n 小、bootstrap p 0.04-0.28（E8 存档），开关不改变这一点；")
    L.append("     开关只回答『崩盘段能否止血』，不为留出段 edge 增加任何证据。")
    L.append("")
    L.append(f"运行耗时 {time.time() - t0:.0f}s")
    (OUT / "summary.txt").write_text("\n".join(L), encoding="utf-8")
    print("\n" + "\n".join(L))


if __name__ == "__main__":
    main()
